name: Release to npm

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org/"

      - name: Remove node_modules before commit
        run: rm -rf node_modules

      - name: Install dependencies
        run: npm install

      - name: Create version bump if needed
        run: npx changeset version

      - name: Commit & push version bump
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git reset -- node_modules
          git commit -m "chore: version bump [skip ci]" || echo "No changes to commit"
          git push

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: npx changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
